In [1]:
import numpy as np

np.zeros(5)

array([0., 0., 0., 0., 0.])

In [2]:
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [3]:
np.empty(4)

array([6.95240439e-310, 9.79020686e-312, 6.95240439e-310, 9.79020686e-312])

In [4]:
np.arange(20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [5]:
np.arange(3,30,5)

array([ 3,  8, 13, 18, 23, 28])

In [9]:
f_num =np.array([24,56,87,89])
s_num=np.array([2,3,4,78])
f_num+s_num

array([ 26,  59,  91, 167])

In [12]:
data=np.array([[24,56,87,89],[56,76,8,7]])
data

array([[24, 56, 87, 89],
       [56, 76,  8,  7]])

In [13]:
data[0][0]

24

In [15]:
data[0,2]

87